/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thuchanhbuoi2.lab02;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;

/**
 *
 * @author huyvu
 */
public class IOFile extends javax.swing.JFrame {

    /**
     * Creates new form IOFile
     */
    public IOFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReadBinFile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        txtText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContent = new javax.swing.JTextField();
        txtWriteBinFile = new javax.swing.JButton();
        btnReadTxtFile = new javax.swing.JButton();
        btnWriteTxtFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReadBinFile.setText("Doc file nhi phan");
        btnReadBinFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadBinFileActionPerformed(evt);
            }
        });

        jLabel1.setText("Ten tap tin");

        jLabel2.setText("Nhap chuoi");

        jLabel3.setText("Noi dung");

        txtWriteBinFile.setText("Ghi file nhi phan");
        txtWriteBinFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWriteBinFileActionPerformed(evt);
            }
        });

        btnReadTxtFile.setText("Doc file van ban");
        btnReadTxtFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadTxtFileActionPerformed(evt);
            }
        });

        btnWriteTxtFile.setText("Ghi file van ban");
        btnWriteTxtFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteTxtFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnWriteTxtFile)
                            .addComponent(txtWriteBinFile))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReadBinFile)
                            .addComponent(btnReadTxtFile)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContent, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReadBinFile)
                    .addComponent(txtWriteBinFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWriteTxtFile)
                    .addComponent(btnReadTxtFile))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtWriteBinFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWriteBinFileActionPerformed
        byte a[] = new byte[20];
        File file;
        int i;
        char s[] = txtText.getText().toCharArray();
        for (i = 0; i < s.length; i++) {
            a[i] = (byte) s[i];

        }

        try {
            file = new File(txtPath.getText());
            FileOutputStream fo = new FileOutputStream(file);
            fo.write(a);
            fo.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtWriteBinFileActionPerformed

    private void btnReadBinFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadBinFileActionPerformed
        byte a[];
        File file;
        try {
            file = new File(txtPath.getText());
            FileInputStream fi = new FileInputStream(file);
            a = new byte[fi.available()];

            fi.read(a);
            fi.close();

            txtContent.setText(new String(a));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReadBinFileActionPerformed

    private void btnWriteTxtFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteTxtFileActionPerformed
        try {
            FileWriter fw = new FileWriter(new File(txtPath.getText()));
            fw.write(txtText.getText());
            fw.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnWriteTxtFileActionPerformed

    private void btnReadTxtFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadTxtFileActionPerformed
        try {
            FileReader fr = new FileReader(new File(txtPath.getText()));
            StringBuffer sb = new StringBuffer();
            char ca[] = new char[5];

            while (fr.ready()) {
                int len = fr.read(ca);
                sb.append(ca, 0, len);
            }
            fr.close();
            txtContent.setText(sb + "");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReadTxtFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IOFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IOFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IOFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IOFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IOFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReadBinFile;
    private javax.swing.JButton btnReadTxtFile;
    private javax.swing.JButton btnWriteTxtFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtContent;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtText;
    private javax.swing.JButton txtWriteBinFile;
    // End of variables declaration//GEN-END:variables
}
